-- public.books definition
-- Drop table
-- DROP TABLE public.books;

create table public.books (
	book_id int4 generated by default as identity( increment by 1 minvalue 1 maxvalue 2147483647 start 1 cache 1 no cycle) not null,
	title text not null,
	author_first_name text not null,
	author_last_name text not null,
	imprint_name text not null,
	is_series bool default false not null,
	series_title text null,
	series_number int4 null,
	publication_year int4 null,
	price numeric null,
	genre_1 text not null,
	genre_2 text null,
	genre_3 text null,
	subject_1 text null,
	subject_2 text null,
	fiction_status text default 'Fiction'::text not null,
	purchase_url text null,
	status text default 'Want'::text not null,
	notes text null,
	imprint_id int4 null,
	publisher_id int4 null,
	constraint books_fixed_pkey primary key (book_id)
);
-- public.books foreign keys

alter table public.books add constraint books_fixed_imprint_id_fkey foreign key (imprint_id) references public.books_imprints(imprint_id);

alter table public.books add constraint books_publisher_fk foreign key (publisher_id) references public.books_publishers(publisher_id);
